name: Access Azure Storage Blob via OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC token request
  contents: read   # Required for actions/checkout

jobs:
  access-blob:
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Download and Display Flag from Blob
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob download \
              --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}" \
              --container-name "${{ vars.AZURE_CONTAINER_NAME }}" \
              --name "${{ vars.AZURE_BLOB_NAME }}" \
              --file /tmp/flag.txt \
              --auth-mode login
            cat /tmp/flag.txt
