name: Get Flag
on: [workflow_dispatch]
 
permissions:
  id-token: write
  contents: read
 
jobs:
  get-flag:
    runs-on: ubuntu-latest
    environment: Azure    
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: azure.training.hacktricks.xyz
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
 
      - name: Download flag
        run: |
          az storage account list
          az storage blob download \
            --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}" \
            --container-name "${{ vars.AZURE_CONTAINER_NAME }}" \
            --name "${{ vars.AZURE_BLOB_NAME }}" \
            --file flag.txt \
            --auth-mode login
      - name: Read flag
        run: |
          cat flag.txt
