name: Get Flag
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: 4470881f-631a-4d27-a0a4-1127671e7776
          tenant-id: e48fa11c-15f3-48a0-a953-8d617222a070
          subscription-id: e48fa11c-15f3-48a0-a953-8d617222a070
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage account list
          az storage blob download \
            --account-name iamazurelab3a3b1f4b3 \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login
      - name: Read flag
        run: |
          cat flag.txt
 
